# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

permissions:
  contents: write
  pull-requests: write

on: [workflow_dispatch]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.tests.outputs.versions }}
    steps:
      - name: Checkout Git
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
          dotnet-quality: ga

      - name: Read Versions
        id: read-versions
        uses: D4nyi/DotNet-Actions/readProjectVersions@fix-errors
        with:
          source_dir: ./src

      - name: Tests
        uses: D4nyi/DotNet-Actions/runTests@fix-errors

  publish:
    name: Publish
    needs: [tests, analyze]
    runs-on: ubuntu-latest
    steps:
      - name: Read Tags
        id: read-tags
        uses: D4nyi/DotNet-Actions/readTags@fix-errors
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Git
        uses: actions/checkout@v6

      - name: Setup .NET
        id: dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          dotnet-quality: ga

      - name: Publish
        uses: D4nyi/DotNet-Actions/publish@fix-errors
        with:
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ needs.read-tags.outputs.tags }}
          versions: ${{ needs.tests.outputs.versions }}
